name: NB Magazine

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 0 * * 1,6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xdg-utils wget xz-utils python3
          sudo apt-get install -y libxcb-cursor0 libxcb-xinerama0 libegl1 libopengl0

      - name: Install Calibre
        run: |
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
          python3 -m venv venv
          source venv/bin/activate
          pip install bs4 requests
          python nybooks.py


      - name: Fetch Epub
        run: |
          wget https://raw.githubusercontent.com/kovidgoyal/calibre/master/recipes/new_york_review_of_books_no_sub.recipe -O NB.recipe
          python replace_NB.py
          ebook-convert NB.recipe output.epub
          ebook-meta output.epub > epub_metadata.txt
          ebook-meta output.epub --get-cover=cover.jpg

      - name: Convert EPUB to PDF
        run: |
          ebook-convert output.epub output.pdf \
              --pdf-page-margin-top 30 \
              --pdf-page-margin-bottom 40 \
              --base-font-size 13 \
              --extra-css "styles_NB.css"

      - name: Move files to folder
        run: |
          full_published_date=$(grep "Title" epub_metadata.txt | grep -o "\[.*\]" | tr -d '[]')
          formatted_date=$(date -d "$full_published_date" +"%Y-%m-%d")
          year=$(date -d "$formatted_date" +"%Y")
          mkdir -p NB/"$year"/"$formatted_date"
          mv output.epub NB/"$year"/"$formatted_date"/NB_"$formatted_date".epub
          mv output.pdf NB/"$year"/"$formatted_date"/NB_"$formatted_date".pdf
          mv cover.jpg NB/"$year"/"$formatted_date"/


      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add NB/*
          git commit -m "Initial commit"
          git push
