name: SA Magazine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xdg-utils wget xz-utils python3
          sudo apt-get install -y libxcb-cursor0 libxcb-xinerama0 libegl1 libopengl0

      - name: Install Calibre
        run: |
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
          python3 -m venv venv
          source venv/bin/activate
          pip install requests bs4
          python SAdate.py


      - name: Fetch Magazine Epub
        run: |
          wget https://raw.githubusercontent.com/kovidgoyal/calibre/master/recipes/scientific_american.recipe -O SA.recipe
          python replace_SA.py
          ebook-convert SA.recipe output_raw.epub
          ebook-meta output_raw.epub > epub_metadata.txt
          ebook-meta output_raw.epub --get-cover=cover.jpg

      - name: Cleanup Epub
        run: |
          unzip -o output_raw.epub -d output_folder
          find output_folder -type f -name "*.html" -exec sed -i 's|<hr[^>]*/><h4[^>]*>On supporting.*ideas shaping our world today.</p><hr[^>]*/>||g' {} \;
          find output_folder -type f -name "*.html" -exec sed -i 's|<hr class="calibre.\{1,2\}" data-block="sciam/raw_html"/>||g' {} \;
          find output_folder -type f -name "*.html" -exec sed -i 's|This article was downloaded by <strong[^>]*>calibre</strong> from ||g' {} \;
          zip -r output.epub output_folder && rm -rf output_folder

      - name: Convert EPUB to PDF
        run: |
          ebook-convert output.epub output.pdf \
              --pdf-page-margin-top 30 \
              --pdf-page-margin-bottom 40 \
              --base-font-size 13 \
              --extra-css "styles_SA.css"

      - name: Create folder
        run: |
          folder_name=$(cat published_date.txt)
          year=$(echo "$folder_name" | cut -d '-' -f 1)
          mkdir -p SA/"$year"/"$folder_name"
          mv output.epub SA/"$year"/"$folder_name"/SA_"$folder_name".epub
          mv output.pdf SA/"$year"/"$folder_name"/SA_"$folder_name".pdf
          mv cover.jpg SA/"$year"/"$folder_name"/


      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add SA/*
          git commit -m "Initial commit"
          git push
